### ISSUE TITLE
Setup project with PostgreSQL

### ISSUE THREAD

**Issue by D-Bhatta** [D-Bhatta/Django-Invoicing#2]
# Setup project with PostgreSQL

**Is your feature request related to a problem? Please describe.**

- Setup the project
- Add mock fixtures
- Integrate with PostgreSQL

### Tasks

- [ ] Create templates: `base.html`, `dummy.html`, `homepage.html`
- [ ] Create static assets
- [ ] Create `homepage` view
- [ ] Delete all tables in `test_main`
- [ ] Delete all tables in `elephantsql1` db
- [ ] Integrate local PostgreSQL in settings
- [ ] Integrate remote PostgreSQL in settings

**Has the feature been requested before?**

No.

**If the feature request is approved, would there be a need for further development in this area?**
No.
