### ISSUE TITLE
Deploy project

### ISSUE THREAD

**Issue by D-Bhatta** [D-Bhatta/Django-Invoicing#3]
# Deploy project

**Is your feature request related to a problem? Please describe.**

- Create PythonAnywhere account
- Deploy project

### Tasks

- [ ] Create PythonAnywhere account
- [ ] Pull from git
- [ ] Create environment
- [ ] Collect static
- [ ] Follow tutorial [here](https://help.pythonanywhere.com/pages/DeployExistingDjangoProject/)
- [ ] Add static assets

**Has the feature been requested before?**

No.

**If the feature request is approved, would there be a need for further development in this area?**
No.
