### ISSUE TITLE
Create a `Homepage`

### ISSUE THREAD

**Issue by D-Bhatta** [D-Bhatta/Django-Invoicing#4]
# Create a `Homepage`

**Is your feature request related to a problem? Please describe.**

- Create a `homepage` page
- Add mock links
- Refactor links into real ones

### Tasks

- [ ] Create a template: `homepage.html`
- [ ] Add cards for each page
- [ ] Add mock links to each card
- [ ] Refactor links into real ones

**Has the feature been requested before?**

No.

**If the feature request is approved, would there be a need for further development in this area?**
No.
