### ISSUE TITLE
Setup authentication

### ISSUE THREAD

**Issue by D-Bhatta** [D-Bhatta/Django-Invoicing#5]
# Setup authentication

**Is your feature request related to a problem? Please describe.**

- Setup authentication
- Show user stuff in homepage only if logged in

### Tasks

- [ ] Create an `users` app
- [ ] Add authentication urls
- [ ] Add authentication templates
- [ ] Refactor homepage to show user stuff only if logged in

**Has the feature been requested before?**

No.

**If the feature request is approved, would there be a need for further development in this area?**
No.
