### ISSUE TITLE
Create Settings page

### ISSUE THREAD

**Issue by D-Bhatta** [D-Bhatta/Django-Invoicing#6]
# Create `Settings` page

**Is your feature request related to a problem? Please describe.**

- Let user specify field names in a form

### Tasks

- [ ] Create a template `settings.html`
- [ ] Create a `settings` view
- [ ] Create a model to store settings
- [ ] Create a form to set default values for fields
- [ ] Add links to change password

**Has the feature been requested before?**

No.

**If the feature request is approved, would there be a need for further development in this area?**
No.
