### ISSUE TITLE
Create Create Invoice page

### ISSUE THREAD

**Issue by D-Bhatta** [D-Bhatta/Django-Invoicing#7]
# Create `Create Invoice` page

**Is your feature request related to a problem? Please describe.**

- Create form for invoice
- Retrieve defaults unless values are specified
- Allow to select if stuff will be printed to invoice or just stored
- Show invoice as HTML

### Tasks

- [ ] Create a `create_invoice.html` template
- [ ] Create an invoice form
- [ ] Create a `create_invoice` view
- [ ] Create an `Invoice` class
- [ ] Create a model to store the invoice data
- [ ] Save invoice in model
- [ ] Create a `view_invoice.html` template and write invoice there

**Has the feature been requested before?**

No.

**If the feature request is approved, would there be a need for further development in this area?**
No.
