### ISSUE TITLE
Create Invoices Dashboard page

### ISSUE THREAD

**Issue by D-Bhatta** [D-Bhatta/Django-Invoicing#9]
# Create `Invoices Dashboard` page

**Is your feature request related to a problem? Please describe.**

- Create an invoices page with index of all invoices

### Tasks

- [ ] Create a template `dashboard.html`
- [ ] Get all invoices for user
- [ ] Display links to all invoices as cards

**Has the feature been requested before?**

No.

**If the feature request is approved, would there be a need for further development in this area?**
No.
